name: Laravel Create and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-laravel:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, curl, libxml, zlib

    - name: Create Laravel Project
      # Kita buat project dengan nama 'temp-app', lalu pindahkan isinya ke folder utama
      run: |
        composer create-project laravel/laravel temp-app
        cp -r temp-app/. .
        rm -rf temp-app

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

